import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased text-slate-800 dark:text-slate-100 bg-white dark:bg-slate-900 h-screen`}>
        <div className='container mx-auto'>{children}</div>
      </body>
    </html>
  )
}
